import '@radix-ui/themes/styles.css';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Theme } from '@radix-ui/themes'
import { AppWrapper } from "@/context/AppContext";


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <AppWrapper>
          <Theme appearance="light" color='gray' radius="small">
            {children}
            {/* <ThemePanel /> */}
          </Theme>
        </AppWrapper>
      </body>
    </html >
  )
}


